#!/bin/bash

# SwiftSync - Quick Deploy to Render
# This script helps you deploy the fixed version to Render.com

echo "🚀 SwiftSync - Deploy to Render"
echo "================================"
echo ""

echo "📋 Pre-Deployment Checklist:"
echo "✓ Fixed Telegram duplicate notifications"
echo "✓ Fixed mobile login issues"
echo "✓ Fixed PWA installation"
echo "✓ Admin dashboard using real data"
echo "✓ Added CORS for mobile support"
echo ""

echo "🔧 Next Steps:"
echo ""
echo "1. Push code to GitHub:"
echo "   git add ."
echo "   git commit -m 'Fixed all mobile and deployment issues'"
echo "   git push origin main"
echo ""
echo "2. Go to Render Dashboard: https://dashboard.render.com"
echo ""
echo "3. Set Environment Variables:"
echo "   PORTAL_USERNAME=your_portal_username"
echo "   PORTAL_PASSWORD=your_portal_password"
echo "   GEMINI_API_KEY=your_gemini_api_key"
echo "   SECRET_ADMIN_KEY=your_secret_admin_key"
echo "   TELEGRAM_BOT_TOKEN=your_telegram_bot_token"
echo "   TELEGRAM_GROUP_ID=your_telegram_group_id"
echo "   TELEGRAM_CHAT_ID=-1003523536992"
echo "   BASE_URL=https://swiftsync-013r.onrender.com"
echo "   RENDER=true"
echo ""
echo "4. Trigger Manual Deploy in Render"
echo ""
echo "5. Test After Deployment:"
echo "   - Health: curl https://swiftsync-013r.onrender.com/health"
echo "   - Sync: curl -X POST https://swiftsync-013r.onrender.com/api/sync-now"
echo "   - Mobile: Open on phone and try login + PWA install"
echo "   - Telegram: Check for notifications (should NOT duplicate)"
echo ""
echo "📱 Install PWA on Mobile:"
echo "   iOS: Safari → Share → Add to Home Screen"
echo "   Android: Chrome → Menu → Install App"
echo ""
echo "🛡️ Admin Dashboard:"
echo "   https://swiftsync-013r.onrender.com/admin-portal?admin_key=YOUR_ADMIN_KEY"
echo ""
echo "✅ All systems ready for production!"
echo ""
